services:
  # zkML ONNX Verifier (Single Service - API + UI)
  - type: web
    name: onnx-verifier
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: HF_TOKEN
        sync: false
    healthCheckPath: /health
